<?php

namespace App\Filament\Resources\Services\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ServiceInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('trello_card_id')
                    ->placeholder('-'),
                TextEntry::make('sitter.name')
                    ->label('Sitter'),
                TextEntry::make('category.name')
                    ->label('Category'),
                TextEntry::make('title'),
                TextEntry::make('slug'),
                TextEntry::make('description')
                    ->columnSpanFull(),
                TextEntry::make('price_per_hour')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_per_day')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_per_visit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_per_week')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_per_month')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('weekend_surcharge_percent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('holiday_surcharge_percent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('early_morning_surcharge_percent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('late_evening_surcharge_percent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bulk_discount_threshold')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bulk_discount_percent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('long_term_discount_days')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('long_term_discount_percent')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('free_consultation')
                    ->boolean(),
                IconEntry::make('free_trial_visit')
                    ->boolean(),
                TextEntry::make('payment_method')
                    ->badge(),
                TextEntry::make('cancellation_hours')
                    ->numeric(),
                TextEntry::make('cancellation_fee_percent')
                    ->numeric(),
                IconEntry::make('home_service')
                    ->boolean(),
                IconEntry::make('sitter_home')
                    ->boolean(),
                TextEntry::make('max_pets')
                    ->numeric(),
                IconEntry::make('is_active')
                    ->boolean(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('service_radius')
                    ->numeric(),
                IconEntry::make('allow_mixed_pet_types')
                    ->boolean(),
                TextEntry::make('minimum_duration')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('maximum_duration')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_structure')
                    ->badge(),
                IconEntry::make('requires_consultation')
                    ->boolean(),
                IconEntry::make('emergency_contact')
                    ->boolean(),
                TextEntry::make('experience_years')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('insurance_coverage')
                    ->boolean(),
                IconEntry::make('vaccination_requirements')
                    ->boolean(),
            ]);
    }
}
