<?php

namespace Database\Seeders;

use App\Models\MapItem;
use App\Models\User;
use Illuminate\Database\Seeder;

class MapItemSeeder extends Seeder
{
    public function run(): void
    {
        // Sprawdzamy czy mamy użytkowników
        $users = User::limit(5)->get();
        if ($users->isEmpty()) {
            $this->command->warn('Brak użytkowników - pomijam tworzenie MapItems');

            return;
        }

        // Tworzymy MapItems jako standalone obiekty
        // (używamy generycznego 'standalone' typu dla demonstracji)

        $mapItems = [
            // Kliniki weterynaryjne w Warszawie
            [
                'user_id' => $users->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 1,
                'latitude' => 52.2297,
                'longitude' => 21.0122,
                'city' => 'Warszawa',
                'voivodeship' => 'mazowieckie',
                'full_address' => 'ul. Marszałkowska 15, 00-061 Warszawa',
                'title' => 'Klinika Weterynaryjna VetCenter',
                'description_short' => 'Nowoczesna klinika weterynaryjna oferująca pełen zakres usług medycznych dla zwierząt.',
                'content_type' => 'service',
                'category_name' => 'Klinika weterynaryjna',
                'category_icon' => 'medical-bag',
                'category_color' => '#10B981',
                'rating_avg' => 4.8,
                'rating_count' => 120,
                'view_count' => 1250,
                'interaction_count' => 85,
                'status' => 'published',
            ],
            [
                'user_id' => $users->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.2166,
                'longitude' => 21.0069,
                'city' => 'Warszawa',
                'voivodeship' => 'mazowieckie',
                'full_address' => 'Pole Mokotowskie, 00-460 Warszawa',
                'title' => 'Park dla Psów - Pole Mokotowskie',
                'description_short' => 'Duży ogrodzony wybieg dla psów z agility i miejscami do wypoczynku.',
                'content_type' => 'service',
                'category_name' => 'Park dla psów',
                'category_icon' => 'dog',
                'category_color' => '#8B5CF6',
                'rating_avg' => 4.5,
                'rating_count' => 89,
                'view_count' => 2340,
                'interaction_count' => 156,
                'status' => 'published',
            ],
            [
                'user_id' => $users->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.2319,
                'longitude' => 21.0067,
                'city' => 'Warszawa',
                'voivodeship' => 'mazowieckie',
                'full_address' => 'ul. Nowy Świat 45, 00-029 Warszawa',
                'title' => 'Sklep Zoologiczny "Zwierzak"',
                'description_short' => 'Pełny asortyment akcesoriów, karmy i zabawek dla zwierząt domowych.',
                'content_type' => 'supplies',
                'category_name' => 'Sklep zoologiczny',
                'category_icon' => 'shopping-bag',
                'category_color' => '#F59E0B',
                'price_from' => 10.00,
                'price_to' => 500.00,
                'rating_avg' => 4.2,
                'rating_count' => 67,
                'view_count' => 890,
                'interaction_count' => 234,
                'status' => 'published',
            ],

            // Kraków
            [
                'user_id' => $users->skip(1)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 50.0647,
                'longitude' => 19.9450,
                'city' => 'Kraków',
                'voivodeship' => 'małopolskie',
                'full_address' => 'ul. Floriańska 22, 31-021 Kraków',
                'title' => 'Szpital Weterynaryjny Animal Care',
                'description_short' => '24-godzinny szpital weterynaryjny z oddziałem intensywnej opieki.',
                'content_type' => 'service',
                'category_name' => 'Szpital weterynaryjny',
                'category_icon' => 'hospital',
                'category_color' => '#EF4444',
                'rating_avg' => 4.7,
                'rating_count' => 156,
                'view_count' => 3240,
                'interaction_count' => 289,
                'status' => 'published',
                'is_featured' => true,
            ],
            [
                'user_id' => $users->skip(1)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 50.0691,
                'longitude' => 19.9544,
                'city' => 'Kraków',
                'voivodeship' => 'małopolskie',
                'full_address' => 'Park Jordana, 30-049 Kraków',
                'title' => 'Park Jordana - Wybieg dla Psów',
                'description_short' => 'Piękny park z dedykowanym obszarem dla psów, blisko centrum miasta.',
                'content_type' => 'service',
                'category_name' => 'Park dla psów',
                'category_icon' => 'dog',
                'category_color' => '#8B5CF6',
                'rating_avg' => 4.6,
                'rating_count' => 92,
                'view_count' => 1890,
                'interaction_count' => 145,
                'status' => 'published',
            ],

            // Gdańsk
            [
                'user_id' => $users->skip(2)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 54.3520,
                'longitude' => 18.6466,
                'city' => 'Gdańsk',
                'voivodeship' => 'pomorskie',
                'full_address' => 'ul. Długa 33, 80-831 Gdańsk',
                'title' => 'Klinika VetGdańsk',
                'description_short' => 'Specjalistyczna klinika z diagnostyką obrazową i chirurgią.',
                'content_type' => 'service',
                'category_name' => 'Klinika weterynaryjna',
                'category_icon' => 'medical-bag',
                'category_color' => '#10B981',
                'rating_avg' => 4.4,
                'rating_count' => 78,
                'view_count' => 980,
                'interaction_count' => 67,
                'status' => 'published',
            ],
            [
                'user_id' => $users->skip(2)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 54.4372,
                'longitude' => 18.5794,
                'city' => 'Gdańsk',
                'voivodeship' => 'pomorskie',
                'full_address' => 'Plaża Jelitkowo, 80-336 Gdańsk',
                'title' => 'Plaża dla Psów - Jelitkowo',
                'description_short' => 'Jedyna oficjalna plaża w Polsce, gdzie psy mogą biegać bez smyczy.',
                'content_type' => 'service',
                'category_name' => 'Plaża dla psów',
                'category_icon' => 'wave',
                'category_color' => '#06B6D4',
                'rating_avg' => 4.8,
                'rating_count' => 203,
                'view_count' => 4560,
                'interaction_count' => 345,
                'status' => 'published',
                'is_featured' => true,
            ],

            // Wrocław
            [
                'user_id' => $users->skip(3)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 51.1079,
                'longitude' => 17.0385,
                'city' => 'Wrocław',
                'voivodeship' => 'dolnośląskie',
                'full_address' => 'ul. Rynek 50, 50-116 Wrocław',
                'title' => 'Centrum Weterynaryjne VetWrocław',
                'description_short' => 'Centrum z pełnym wyposażeniem diagnostycznym i zespołem specjalistów.',
                'content_type' => 'service',
                'category_name' => 'Centrum weterynaryjne',
                'category_icon' => 'building-office',
                'category_color' => '#10B981',
                'rating_avg' => 4.6,
                'rating_count' => 134,
                'view_count' => 1670,
                'interaction_count' => 178,
                'status' => 'published',
            ],

            // Poznań
            [
                'user_id' => $users->skip(4)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.4064,
                'longitude' => 16.9252,
                'city' => 'Poznań',
                'voivodeship' => 'wielkopolskie',
                'full_address' => 'ul. Święty Marcin 25, 61-806 Poznań',
                'title' => 'Przychodnia Weterynaryjna PetMed',
                'description_short' => 'Nowoczesna przychodnia z gabinetem stomatologicznym dla zwierząt.',
                'content_type' => 'service',
                'category_name' => 'Przychodnia weterynaryjna',
                'category_icon' => 'medical-bag',
                'category_color' => '#10B981',
                'rating_avg' => 4.3,
                'rating_count' => 89,
                'view_count' => 1230,
                'interaction_count' => 123,
                'status' => 'published',
            ],
            [
                'user_id' => $users->skip(4)->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.4210,
                'longitude' => 16.9474,
                'city' => 'Poznań',
                'voivodeship' => 'wielkopolskie',
                'full_address' => 'Park Cytadela, 61-663 Poznań',
                'title' => 'Park Cytadela - Teren dla Psów',
                'description_short' => 'Historyczny park z wydzielonym terenem spacerowym dla psów.',
                'content_type' => 'service',
                'category_name' => 'Park dla psów',
                'category_icon' => 'dog',
                'category_color' => '#8B5CF6',
                'rating_avg' => 4.2,
                'rating_count' => 67,
                'view_count' => 890,
                'interaction_count' => 89,
                'status' => 'published',
            ],

            // Dodatkowe miejsca specjalistyczne
            [
                'user_id' => $users->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.2000,
                'longitude' => 21.0500,
                'city' => 'Warszawa',
                'voivodeship' => 'mazowieckie',
                'full_address' => 'ul. Puławska 120, 02-566 Warszawa',
                'title' => 'Centrum Rehabilitacji Zwierząt',
                'description_short' => 'Specjalistyczne centrum rehabilitacji i fizjoterapii dla zwierząt.',
                'content_type' => 'service',
                'category_name' => 'Rehabilitacja zwierząt',
                'category_icon' => 'heart',
                'category_color' => '#F472B6',
                'price_from' => 80.00,
                'price_to' => 200.00,
                'rating_avg' => 4.9,
                'rating_count' => 45,
                'view_count' => 560,
                'interaction_count' => 67,
                'status' => 'published',
                'is_featured' => true,
            ],
            [
                'user_id' => $users->first()->id,
                'mappable_type' => 'standalone',
                'mappable_id' => 2,
                'latitude' => 52.1500,
                'longitude' => 21.0800,
                'city' => 'Warszawa',
                'voivodeship' => 'mazowieckie',
                'full_address' => 'ul. Wilanowska 250, 02-665 Warszawa',
                'title' => 'Hotel dla Zwierząt Pet Paradise',
                'description_short' => 'Luksusowy hotel dla zwierząt z ogrodem i profesjonalną opieką.',
                'content_type' => 'service',
                'category_name' => 'Hotel dla zwierząt',
                'category_icon' => 'building',
                'category_color' => '#A78BFA',
                'price_from' => 50.00,
                'price_to' => 150.00,
                'rating_avg' => 4.7,
                'rating_count' => 89,
                'view_count' => 1340,
                'interaction_count' => 198,
                'status' => 'published',
            ],
        ];

        foreach ($mapItems as $index => $item) {
            $item['mappable_id'] = $index + 1; // Unikalne ID dla każdego elementu
            MapItem::create($item);
        }

        $this->command->info('Utworzono '.count($mapItems).' pozycji na mapie.');
    }
}
