version: '3.8'

services:
  nominatim-db:
    image: postgis/postgis:16-3.4
    container_name: pethelp-nominatim-db
    environment:
      POSTGRES_DB: nominatim
      POSTGRES_USER: nominatim
      POSTGRES_PASSWORD: pethelp_nominatim_2025
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - nominatim_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=2GB
      -c effective_cache_size=6GB
      -c maintenance_work_mem=512MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=64MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: pethelp-nominatim
    environment:
      # PostgreSQL settings
      PBF_URL: https://download.geofabrik.de/europe/poland-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/poland-updates/
      POSTGRES_HOST: nominatim-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: nominatim
      POSTGRES_USER: nominatim
      POSTGRES_PASSWORD: pethelp_nominatim_2025

      # Import settings optimized for Poland
      IMPORT_WIKIPEDIA: false
      IMPORT_US_POSTCODES: false
      IMPORT_GB_POSTCODES: false
      THREADS: 4

      # Performance tuning
      NOMINATIM_TOKENIZER: icu
      NOMINATIM_DATABASE_WEBUSER: nominatim
      NOMINATIM_API_REQUEST_TIMEOUT: 60
      NOMINATIM_LOOKUP_MAX_COUNT: 50
      NOMINATIM_REVERSE_MAX_RANK: 30

      # Poland-specific configuration
      NOMINATIM_ADDRESS_LEVEL_CONFIG: |
        {
          "country": 2,
          "state": 4,
          "county": 8,
          "city": 10,
          "suburb": 12,
          "village": 14,
          "town": 10,
          "neighbourhood": 16,
          "postcode": 5
        }
    ports:
      - "8080:8080"
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main
      - nominatim_flatnode:/nominatim/flatnode
    depends_on:
      - nominatim-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s

  # Optional: Redis for caching API responses
  nominatim-redis:
    image: redis:7-alpine
    container_name: pethelp-nominatim-redis
    ports:
      - "6379:6379"
    volumes:
      - nominatim_redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

volumes:
  nominatim_db_data:
    driver: local
  nominatim_data:
    driver: local
  nominatim_flatnode:
    driver: local
  nominatim_redis_data:
    driver: local

networks:
  default:
    name: pethelp-nominatim-network
    driver: bridge